version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123!
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: mypassword123!
      DB_NAME: coding-challenge
    ports:
      - "3000:3000"
    depends_on:
      - db
